# Generated by Django 4.2.4 on 2023-08-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
